use coopmilk
db.usine1.insertMany([{
    "Num_Automate": 1,
    "Temp_Cuve": 3.7,
    "Temp_Ext": 10.6,
    "Poids_Lait_Cuve": 3599,
    "Mesure_Ph": 7,
    "Mesure_K+": 39,
    "Concentration_NaCl": 1.3,
    "Niv_Bact_Salm": 3,
    "Niv_Bact_E-coli": 1,
    "Niv_Bact_List": 0
   },
   {
    "Num_Automate": 2,
    "Temp_Cuve": 3.8,
    "Temp_Ext": 8.1,
    "Poids_Lait_Cuve": 3665,
    "Mesure_Ph": 7.2,
    "Mesure_K+": 42,
    "Concentration_NaCl": 2.2,
    "Niv_Bact_Salm": 0,
    "Niv_Bact_E-coli": 3,
    "Niv_Bact_List": 1
   },
   {
    "Num_Automate": 3,
    "Temp_Cuve": 3.4,
    "Temp_Ext": 9.6,
    "Poids_Lait_Cuve": 4022,
    "Mesure_Ph": 7.1,
    "Mesure_K+": 37,
    "Concentration_NaCl": 1.6,
    "Niv_Bact_Salm": 3,
    "Niv_Bact_E-coli": 3,
    "Niv_Bact_List": 2
   },
   {
    "Num_Automate": 4,
    "Temp_Cuve": 3.2,
    "Temp_Ext": 13.7,
    "Poids_Lait_Cuve": 4252,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 44,
    "Concentration_NaCl": 2.1,
    "Niv_Bact_Salm": 0,
    "Niv_Bact_E-coli": 3,
    "Niv_Bact_List": 1
   },
   {
    "Num_Automate": 5,
    "Temp_Cuve": 3.4,
    "Temp_Ext": 13.4,
    "Poids_Lait_Cuve": 3852,
    "Mesure_Ph": 7.1,
    "Mesure_K+": 46,
    "Concentration_NaCl": 3.2,
    "Niv_Bact_Salm": 2,
    "Niv_Bact_E-coli": 3,
    "Niv_Bact_List": 2
   },
   {
    "Num_Automate": 6,
    "Temp_Cuve": 3.1,
    "Temp_Ext": 11.7,
    "Poids_Lait_Cuve": 4517,
    "Mesure_Ph": 7,
    "Mesure_K+": 44,
    "Concentration_NaCl": 2.2,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 7,
    "Niv_Bact_List": 1
   },
   {
    "Num_Automate": 7,
    "Temp_Cuve": 3.2,
    "Temp_Ext": 11.7,
    "Poids_Lait_Cuve": 3815,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 43,
    "Concentration_NaCl": 2.1,
    "Niv_Bact_Salm": 0,
    "Niv_Bact_E-coli": 6,
    "Niv_Bact_List": 0
   },
   {
    "Num_Automate": 8,
    "Temp_Cuve": 3.5,
    "Temp_Ext": 12.7,
    "Poids_Lait_Cuve": 3558,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 36,
    "Concentration_NaCl": 1.7,
    "Niv_Bact_Salm": 3,
    "Niv_Bact_E-coli": 1,
    "Niv_Bact_List": 2
   },
   {
    "Num_Automate": 9,
    "Temp_Cuve": 3.1,
    "Temp_Ext": 13.9,
    "Poids_Lait_Cuve": 3655,
    "Mesure_Ph": 7,
    "Mesure_K+": 44,
    "Concentration_NaCl": 3.1,
    "Niv_Bact_Salm": 2,
    "Niv_Bact_E-coli": 4,
    "Niv_Bact_List": 3
   },
   {
    "Num_Automate": 10,
    "Temp_Cuve": 3.3,
    "Temp_Ext": 9.1,
    "Poids_Lait_Cuve": 3738,
    "Mesure_Ph": 7.1,
    "Mesure_K+": 37,
    "Concentration_NaCl": 1.9,
    "Niv_Bact_Salm": 2,
    "Niv_Bact_E-coli": 0,
    "Niv_Bact_List": 2
   }])

db.usine2.insertMany([{
    "Num_Automate": 1,
    "Temp_Cuve": 3.7,
    "Temp_Ext": 12.4,
    "Poids_Lait_Cuve": 4135,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 42,
    "Concentration_NaCl": 3.6,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 2,
    "Niv_Bact_List": 4
   },
   {
    "Num_Automate": 2,
    "Temp_Cuve": 2.9,
    "Temp_Ext": 13.6,
    "Poids_Lait_Cuve": 4006,
    "Mesure_Ph": 7.1,
    "Mesure_K+": 39,
    "Concentration_NaCl": 3.5,
    "Niv_Bact_Salm": 2,
    "Niv_Bact_E-coli": 7,
    "Niv_Bact_List": 4
   },
   {
    "Num_Automate": 3,
    "Temp_Cuve": 3.4,
    "Temp_Ext": 12.8,
    "Poids_Lait_Cuve": 4326,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 38,
    "Concentration_NaCl": 3.6,
    "Niv_Bact_Salm": 2,
    "Niv_Bact_E-coli": 4,
    "Niv_Bact_List": 2
   },
   {
    "Num_Automate": 4,
    "Temp_Cuve": 3,
    "Temp_Ext": 8.6,
    "Poids_Lait_Cuve": 3841,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 46,
    "Concentration_NaCl": 3.5,
    "Niv_Bact_Salm": 0,
    "Niv_Bact_E-coli": 6,
    "Niv_Bact_List": 4
   },
   {
    "Num_Automate": 5,
    "Temp_Cuve": 3.1,
    "Temp_Ext": 8.5,
    "Poids_Lait_Cuve": 3749,
    "Mesure_Ph": 7.2,
    "Mesure_K+": 38,
    "Concentration_NaCl": 3,
    "Niv_Bact_Salm": 2,
    "Niv_Bact_E-coli": 2,
    "Niv_Bact_List": 0
   },
   {
    "Num_Automate": 6,
    "Temp_Cuve": 2.8,
    "Temp_Ext": 8.9,
    "Poids_Lait_Cuve": 3518,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 42,
    "Concentration_NaCl": 2.7,
    "Niv_Bact_Salm": 2,
    "Niv_Bact_E-coli": 7,
    "Niv_Bact_List": 2
   },
   {
    "Num_Automate": 7,
    "Temp_Cuve": 3.8,
    "Temp_Ext": 12.5,
    "Poids_Lait_Cuve": 3554,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 38,
    "Concentration_NaCl": 2.2,
    "Niv_Bact_Salm": 0,
    "Niv_Bact_E-coli": 4,
    "Niv_Bact_List": 4
   },
   {
    "Num_Automate": 8,
    "Temp_Cuve": 2.5,
    "Temp_Ext": 9.8,
    "Poids_Lait_Cuve": 3906,
    "Mesure_Ph": 7,
    "Mesure_K+": 39,
    "Concentration_NaCl": 3.5,
    "Niv_Bact_Salm": 0,
    "Niv_Bact_E-coli": 6,
    "Niv_Bact_List": 0
   },
   {
    "Num_Automate": 9,
    "Temp_Cuve": 2.6,
    "Temp_Ext": 11.4,
    "Poids_Lait_Cuve": 4207,
    "Mesure_Ph": 6.9,
    "Mesure_K+": 35,
    "Concentration_NaCl": 3.5,
    "Niv_Bact_Salm": 2,
    "Niv_Bact_E-coli": 0,
    "Niv_Bact_List": 4
   },
   {
    "Num_Automate": 10,
    "Temp_Cuve": 3.7,
    "Temp_Ext": 11.9,
    "Poids_Lait_Cuve": 3919,
    "Mesure_Ph": 7.2,
    "Mesure_K+": 45,
    "Concentration_NaCl": 1.6,
    "Niv_Bact_Salm": 0,
    "Niv_Bact_E-coli": 1,
    "Niv_Bact_List": 3
   }])

db.usine3.insertMany([{
    "Num_Automate": 1,
    "Temp_Cuve": 3,
    "Temp_Ext": 9.6,
    "Poids_Lait_Cuve": 4374,
    "Mesure_Ph": 7.2,
    "Mesure_K+": 38,
    "Concentration_NaCl": 2,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 0,
    "Niv_Bact_List": 4
   },
   {
    "Num_Automate": 2,
    "Temp_Cuve": 3.5,
    "Temp_Ext": 11.2,
    "Poids_Lait_Cuve": 4533,
    "Mesure_Ph": 6.9,
    "Mesure_K+": 44,
    "Concentration_NaCl": 1.3,
    "Niv_Bact_Salm": 2,
    "Niv_Bact_E-coli": 5,
    "Niv_Bact_List": 0
   },
   {
    "Num_Automate": 3,
    "Temp_Cuve": 2.6,
    "Temp_Ext": 12.1,
    "Poids_Lait_Cuve": 3691,
    "Mesure_Ph": 7,
    "Mesure_K+": 44,
    "Concentration_NaCl": 3.4,
    "Niv_Bact_Salm": 3,
    "Niv_Bact_E-coli": 4,
    "Niv_Bact_List": 0
   },
   {
    "Num_Automate": 4,
    "Temp_Cuve": 2.9,
    "Temp_Ext": 11.3,
    "Poids_Lait_Cuve": 3631,
    "Mesure_Ph": 7,
    "Mesure_K+": 38,
    "Concentration_NaCl": 2.5,
    "Niv_Bact_Salm": 3,
    "Niv_Bact_E-coli": 5,
    "Niv_Bact_List": 1
   },
   {
    "Num_Automate": 5,
    "Temp_Cuve": 3.8,
    "Temp_Ext": 12.3,
    "Poids_Lait_Cuve": 4155,
    "Mesure_Ph": 7.2,
    "Mesure_K+": 47,
    "Concentration_NaCl": 2.3,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 1,
    "Niv_Bact_List": 1
   },
   {
    "Num_Automate": 6,
    "Temp_Cuve": 2.8,
    "Temp_Ext": 9.5,
    "Poids_Lait_Cuve": 4240,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 41,
    "Concentration_NaCl": 3.6,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 7,
    "Niv_Bact_List": 3
   },
   {
    "Num_Automate": 7,
    "Temp_Cuve": 3.6,
    "Temp_Ext": 14,
    "Poids_Lait_Cuve": 4432,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 44,
    "Concentration_NaCl": 3.7,
    "Niv_Bact_Salm": 0,
    "Niv_Bact_E-coli": 3,
    "Niv_Bact_List": 2
   },
   {
    "Num_Automate": 8,
    "Temp_Cuve": 3.9,
    "Temp_Ext": 11.7,
    "Poids_Lait_Cuve": 4423,
    "Mesure_Ph": 6.9,
    "Mesure_K+": 47,
    "Concentration_NaCl": 1.5,
    "Niv_Bact_Salm": 0,
    "Niv_Bact_E-coli": 1,
    "Niv_Bact_List": 1
   },
   {
    "Num_Automate": 9,
    "Temp_Cuve": 2.7,
    "Temp_Ext": 9,
    "Poids_Lait_Cuve": 4086,
    "Mesure_Ph": 7.1,
    "Mesure_K+": 42,
    "Concentration_NaCl": 1,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 1,
    "Niv_Bact_List": 2
   },
   {
    "Num_Automate": 10,
    "Temp_Cuve": 4,
    "Temp_Ext": 11.5,
    "Poids_Lait_Cuve": 4349,
    "Mesure_Ph": 7,
    "Mesure_K+": 45,
    "Concentration_NaCl": 3.1,
    "Niv_Bact_Salm": 0,
    "Niv_Bact_E-coli": 6,
    "Niv_Bact_List": 1
   }])

db.usine4.insertMany([{
    "Num_Automate": 1,
    "Temp_Cuve": 3.6,
    "Temp_Ext": 13.2,
    "Poids_Lait_Cuve": 3781,
    "Mesure_Ph": 6.9,
    "Mesure_K+": 43,
    "Concentration_NaCl": 3.4,
    "Niv_Bact_Salm": 3,
    "Niv_Bact_E-coli": 5,
    "Niv_Bact_List": 1
   },
   {
    "Num_Automate": 2,
    "Temp_Cuve": 3.5,
    "Temp_Ext": 11.4,
    "Poids_Lait_Cuve": 4043,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 44,
    "Concentration_NaCl": 2,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 6,
    "Niv_Bact_List": 1
   },
   {
    "Num_Automate": 3,
    "Temp_Cuve": 3.4,
    "Temp_Ext": 13.9,
    "Poids_Lait_Cuve": 4258,
    "Mesure_Ph": 7,
    "Mesure_K+": 41,
    "Concentration_NaCl": 1.3,
    "Niv_Bact_Salm": 0,
    "Niv_Bact_E-coli": 5,
    "Niv_Bact_List": 1
   },
   {
    "Num_Automate": 4,
    "Temp_Cuve": 2.9,
    "Temp_Ext": 8.5,
    "Poids_Lait_Cuve": 3517,
    "Mesure_Ph": 6.9,
    "Mesure_K+": 36,
    "Concentration_NaCl": 2.7,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 1,
    "Niv_Bact_List": 0
   },
   {
    "Num_Automate": 5,
    "Temp_Cuve": 3.4,
    "Temp_Ext": 12.4,
    "Poids_Lait_Cuve": 4189,
    "Mesure_Ph": 7,
    "Mesure_K+": 38,
    "Concentration_NaCl": 3.4,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 0,
    "Niv_Bact_List": 3
   },
   {
    "Num_Automate": 6,
    "Temp_Cuve": 2.5,
    "Temp_Ext": 12.9,
    "Poids_Lait_Cuve": 3892,
    "Mesure_Ph": 7.1,
    "Mesure_K+": 43,
    "Concentration_NaCl": 2.6,
    "Niv_Bact_Salm": 3,
    "Niv_Bact_E-coli": 1,
    "Niv_Bact_List": 3
   },
   {
    "Num_Automate": 7,
    "Temp_Cuve": 3.5,
    "Temp_Ext": 10.9,
    "Poids_Lait_Cuve": 4569,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 44,
    "Concentration_NaCl": 3.6,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 6,
    "Niv_Bact_List": 1
   },
   {
    "Num_Automate": 8,
    "Temp_Cuve": 2.9,
    "Temp_Ext": 12.2,
    "Poids_Lait_Cuve": 4063,
    "Mesure_Ph": 7.1,
    "Mesure_K+": 37,
    "Concentration_NaCl": 1.7,
    "Niv_Bact_Salm": 3,
    "Niv_Bact_E-coli": 4,
    "Niv_Bact_List": 1
   },
   {
    "Num_Automate": 9,
    "Temp_Cuve": 3,
    "Temp_Ext": 13.2,
    "Poids_Lait_Cuve": 3949,
    "Mesure_Ph": 7.2,
    "Mesure_K+": 36,
    "Concentration_NaCl": 1.2,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 5,
    "Niv_Bact_List": 4
   },
   {
    "Num_Automate": 10,
    "Temp_Cuve": 3.4,
    "Temp_Ext": 10.8,
    "Poids_Lait_Cuve": 3773,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 38,
    "Concentration_NaCl": 2.6,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 0,
    "Niv_Bact_List": 1
   }])

db.usine5.insertMany([{
    "Num_Automate": 1,
    "Temp_Cuve": 3.2,
    "Temp_Ext": 10.1,
    "Poids_Lait_Cuve": 3562,
    "Mesure_Ph": 7.2,
    "Mesure_K+": 39,
    "Concentration_NaCl": 1.4,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 7,
    "Niv_Bact_List": 4
   },
   {
    "Num_Automate": 2,
    "Temp_Cuve": 2.5,
    "Temp_Ext": 12.3,
    "Poids_Lait_Cuve": 4146,
    "Mesure_Ph": 7.2,
    "Mesure_K+": 37,
    "Concentration_NaCl": 1.5,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 2,
    "Niv_Bact_List": 3
   },
   {
    "Num_Automate": 3,
    "Temp_Cuve": 3.1,
    "Temp_Ext": 11,
    "Poids_Lait_Cuve": 3828,
    "Mesure_Ph": 7.1,
    "Mesure_K+": 35,
    "Concentration_NaCl": 3.1,
    "Niv_Bact_Salm": 0,
    "Niv_Bact_E-coli": 3,
    "Niv_Bact_List": 1
   },
   {
    "Num_Automate": 4,
    "Temp_Cuve": 3.1,
    "Temp_Ext": 10.8,
    "Poids_Lait_Cuve": 4099,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 47,
    "Concentration_NaCl": 1,
    "Niv_Bact_Salm": 3,
    "Niv_Bact_E-coli": 6,
    "Niv_Bact_List": 3
   },
   {
    "Num_Automate": 5,
    "Temp_Cuve": 2.7,
    "Temp_Ext": 9.1,
    "Poids_Lait_Cuve": 4573,
    "Mesure_Ph": 7.1,
    "Mesure_K+": 40,
    "Concentration_NaCl": 3,
    "Niv_Bact_Salm": 0,
    "Niv_Bact_E-coli": 0,
    "Niv_Bact_List": 4
   },
   {
    "Num_Automate": 6,
    "Temp_Cuve": 3.8,
    "Temp_Ext": 9.7,
    "Poids_Lait_Cuve": 4373,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 44,
    "Concentration_NaCl": 2.5,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 0,
    "Niv_Bact_List": 0
   },
   {
    "Num_Automate": 7,
    "Temp_Cuve": 2.7,
    "Temp_Ext": 10.7,
    "Poids_Lait_Cuve": 4165,
    "Mesure_Ph": 6.9,
    "Mesure_K+": 47,
    "Concentration_NaCl": 2.2,
    "Niv_Bact_Salm": 3,
    "Niv_Bact_E-coli": 2,
    "Niv_Bact_List": 0
   },
   {
    "Num_Automate": 8,
    "Temp_Cuve": 3.6,
    "Temp_Ext": 13.5,
    "Poids_Lait_Cuve": 4447,
    "Mesure_Ph": 7,
    "Mesure_K+": 46,
    "Concentration_NaCl": 2.6,
    "Niv_Bact_Salm": 3,
    "Niv_Bact_E-coli": 3,
    "Niv_Bact_List": 1
   },
   {
    "Num_Automate": 9,
    "Temp_Cuve": 2.6,
    "Temp_Ext": 13.7,
    "Poids_Lait_Cuve": 3753,
    "Mesure_Ph": 6.8,
    "Mesure_K+": 44,
    "Concentration_NaCl": 2.1,
    "Niv_Bact_Salm": 1,
    "Niv_Bact_E-coli": 0,
    "Niv_Bact_List": 0
   },
   {
    "Num_Automate": 10,
    "Temp_Cuve": 3.5,
    "Temp_Ext": 10.3,
    "Poids_Lait_Cuve": 4388,
    "Mesure_Ph": 7,
    "Mesure_K+": 35,
    "Concentration_NaCl": 1.3,
    "Niv_Bact_Salm": 2,
    "Niv_Bact_E-coli": 3,
    "Niv_Bact_List": 4
   }])
